### ISSUE TITLE
[Message, Toast] TypeError: context.selectComponent is not a function

### ISSUE THREAD

**Issue by liuyulvv** [Tencent/tdesign-miniprogram#2778]
### tdesign-miniprogram 版本

1.4.0可以重现

### 重现步骤

``` json
  "usingComponents": {
    "t-message": "tdesign-miniprogram/message/message",
    "t-toast": "tdesign-miniprogram/toast/toast"
  }
```

```html
  <t-message id="t-message" />
  <t-toast id="t-toast" />
```

```javascript

import Message from 'tdesign-miniprogram/message/index';
import Toast from 'tdesign-miniprogram/toast/index';

...
            Message.error({
              context: this,
              offset: [50, 32],
              duration: 5000,
              content: 'error文案"',
            });


            Toast({
              context: this,
              selector: '#t-toast',
              message: '成功文案',
              theme: 'success',
              direction: 'column',
            });
...
```

真机调试:

```
WAServiceMainContext.js:1 MiniProgramError
context.selectComponent is not a function
TypeError: context.selectComponent is not a function
at selectComponent (miniprogram_npm/tdesign-miniprogram/common/utils.js:160:40)
at showMessage (miniprogram_npm/tdesign-miniprogram/message/index.js:16:33)
at showMessage (miniprogram_npm/tdesign-miniprogram/message/index.js:37:16)
at error (pages/pages/index/index.ts:223:21)
```

```
WAServiceMainContext.js:1 MiniProgramError
context.selectComponent is not a function
TypeError: context.selectComponent is not a function
at selectComponent (miniprogram_npm/tdesign-miniprogram/common/utils.js:160:40)
at Toast (miniprogram_npm/tdesign-miniprogram/toast/index.js:16:33)
at Object.fail (pages/pages/index/index.ts:229:18)
```

### 基础库版本

3.4.3

**Comment by betavs** [comment]
经测试无法复现，可能是 `this` 指向导致异常可以自行排查一下，或者提供完整代码

**Comment by 745740681** [comment]
message 这个组件不能在uniapp中的组合式api中使用吗
